name: Build and Deploy (Production)

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    uses: ./.github/workflows/_ci.yml
    with:
      environment: "production"
      AZURE_SERVER_APP_NAME: Ai-Hub-BackEnd
      AZURE_RESOURCE_GROUP_NAME: Ai-Hub
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.PROD_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.PROD_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.PROD_AZURE_SUBSCRIPTION_ID }}
      AZURE_SWA_DEPLOY_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_ROCK_0E27C2600 }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.PROD_VITE_CLERK_PUBLISHABLE_KEY }}
      VITE_API_BASE_URL: ${{ secrets.PROD_VITE_API_BASE_URL }}
      VITE_STRIPE_PUBLIC_KEY: ${{ secrets.PROD_VITE_STRIPE_PUBLIC_KEY }}
