name: Build and Deploy (QA)

on:
  push:
    branches: ["qa"]

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_sloane:
    uses: ./.github/workflows/_ci.yml
    with:
      environment: "qa"
      AZURE_SERVER_APP_NAME: sloane-qa-backend
      AZURE_RESOURCE_GROUP_NAME: Ai-Hub
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.QA_AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.QA_AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.QA_AZURE_SUBSCRIPTION_ID }}
      AZURE_SWA_DEPLOY_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_TREE_048460100 }}
      VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.QA_VITE_CLERK_PUBLISHABLE_KEY }}
      VITE_API_BASE_URL: ${{ secrets.QA_VITE_API_BASE_URL }}
      VITE_STRIPE_PUBLIC_KEY: ${{ secrets.QA_VITE_STRIPE_PUBLIC_KEY }}
